catalog/urls.py
#from django.urls import path
#from .import views



#urlpatterns = [
    #path('', views.index, name='index'),
#]

catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date


# Create your models here.

class Genre(models.Model):
    name = models.CharField(max_length=120,
                            help_text='Введите жанр',
                            verbose_name='Жанр книги')

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(max_length=20,
                            help_text='Введите язык книги',
                            verbose_name='Язык книги')

    def __str__(self):
        return self.name


class Author(models.Model):
    first_name = models.CharField(max_length=100,
                                  help_text='Введите имя автора',
                                  verbose_name='Имя автора')
    last_name = models.CharField(max_length=100,
                                 help_text='Введите фамилию автора',
                                 verbose_name='Фамилия автора'
                                 )
    date_of_birth = models.DateField(help_text='Введите дату рождения',
                                     verbose_name='Дата рождения',
                                     null=True, blank=True)
    date_of_death = models.DateField(help_text='Введите дату смери',
                                     verbose_name='Дата смерти',
                                     null=True, blank=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class Book(models.Model):
    title = models.CharField(max_length=200,
                             help_text='Введите название книги',
                             verbose_name='Название кнгиги',
                             )
    genre = models.ForeignKey('Genre', on_delete=models.CASCADE,
                              help_text='Выберите жанр',
                              verbose_name='Жанр',
                              )
    language = models.ForeignKey('Language', on_delete=models.CASCADE,
                                 help_text='Выберите язык книги',
                                 verbose_name='Язык книги', null=True)
    author = models.ManyToManyField('Author',
                                    help_text='Выберите автора книги',
                                    verbose_name='Автор книги', )
    summary = models.TextField(max_length=500,
                               help_text='Введите краткое описание книги',
                               verbose_name='Описание книги', )
    isbn = models.CharField(max_length=13, help_text='''Введите ISBN книги. 
                                                        Должно быть 13 символов''',
                            verbose_name='ISBN книги')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book_detail', args=[str(self.pk)])


def display_author(self):
    return ', '.join([author.last_name for author in self.author.all()])


display_author.short_description = 'Авторы'


class Status(models.Model):
    name = models.CharField(max_length=20, help_text='Введите статус экземпляра книги',
                            verbose_name='Статус экземпляра книги')

    def __str__(self):
        return self.name


class BookInstance(models.Model):
    book = models.ForeignKey('Book', on_delete=models.CASCADE, null=True)
    inv_nom = models.CharField(max_length=20, null=True, help_text='Введите инвентарный номер',
                               verbose_name='Инвентарный номер')
    status = models.ForeignKey('Status', on_delete=models.CASCADE, null=True,
                               help_text='Изменить состояние экземпляра', verbose_name='Состояние экземпляра')
    imprint = models.CharField(max_length=200, help_text='Введите издательство и год выпуска',
                               verbose_name='Издательство')
    due_back = models.DateField(null=True, blank=True, help_text='Введите конец срока статуса',
                                verbose_name='Дата окончания статуса')

    borrower = models.ForeignKey(User, on_delete=models.SET_NULL,
                                 null=True, blank=True, help_text='Веберите заказчика книги',
                                 verbose_name='Заказчик')
    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    def __str__(self):
        return f'{self.inv_nom} {self.book} {self.status}'

catalog/templates/catalog/author_add.html
{% extends 'base_generic.html' %}
{% block content %}
  <table class="table">
      <thead>
          <th>ID</th>
          <th>~~~Имя~~~</th>
          <th>Фамилия</th>
          <th></th>
      </thead>
      {% if author %}
        {% for author in author.all %}
          <tr class="table-light">
              <td>{{ author.id }}</td>
              <td>{{ author.first_name }}</td>
              <td>{{ author.last_name }}</td>
              <td>
                  <a href="/edit1/{{ author.id }}" class="btn btn-primary">Изменить</a>
                  <a href="/delete/{{ author.id }}" class="btn btn-danger">Удалить</a>
              </td>
          </tr>
        {% endfor %}
      {% else %}
       <p>В базе данных нет авторов</p>
      {% endif %}
  </table>

<h3>Добавить в БД автора книги</h3>
<form method="post" action="/create/">
    {% csrf_token %}
    <table class="table">
        {{form}}
    </table>
    <input type="submit" value="Сохранить" class="btn btn-primary">
</form>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends 'base_generic.html' %}
{% block content %}
<h1 class="display-4 mb-4">Список авторов</h1>
{% if author_list %}
{% for author in author_list.all %}
<p class="lead">
    {{author.first_name}} {{author.last_name}},
    <strong>Родился - </strong> {{ author.date_of_birth}}
    {% if author.date_of_death %}}
    <strong>Умер - </strong> {{ author.date_of_death}}
    {% else %}
    <strong> Автор еще жив</strong>
    {% endif %}
</p>
{% endfor %}
{% else %}
<p class="lead"> В базе нет авторов </p>
{% endif %}
{% endblock %}

catalog/templates/catalog/book_confirm_delete.html
{% extends "base_generic.html" %}

{% block  content %}
  <h1>Удаление книги</h1>
  <p> Вы уверены, что хотите удалить книгу: {{ book }}?</p>
<form action="" method="post">
    {% csrf_token %}
    <input action="" type="submit" value="Да, удалить">

</form>

{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Название книги: {{ book.title }}</h1>
<p><strong>Жанр: </strong> {{ book.genre }}</p>
<p><strong>Аннотация: </strong> {{ book.summary }}</p>
<p><strong>ISBN </strong> {{ book.isbn }}</p>
<p><strong>Язык: </strong> {{ book.language }}</p>
{% for author in book.author.all %}
<p><strong>Автор: </strong><a href="">{{ author.first_name }}
    {{ author.last_name }}</a></p>
{% endfor %}
<div class="#" style="margin-top:20px; margin-left:20px">
    <h4>Количество экземпляров книг в БД</h4>
    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 1 %} text-succces
                      {% elif copy.status == 2 %} text-danger
                      {% else %} text-warning
                      {% endif %}">
        {{ copy.get_status_display }}
    </p>
    <p><strong>Издательство: </strong> {{ copy.imprint }}</p>
    <p class="text-muted"><strong>Инвентарный номер: </strong> {{ copy.id }}</p>
    <p><strong>Статус экземпляра книги: </strong> {{ copy.status }}</p>
    {% endfor %}
</div>

{% endblock %}

<p><strong>Автор: </strong><a href=""> {{ author.first_name }}
    {{ author.last_name }}

</a></p>

catalog/templates/catalog/book_form.html
{% extends "base_generic.html" %}

{% block  content %}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Сохранить">

</form>

{% endblock %}

catalog/templates/catalog/book_list.html
{% extends 'base_generic.html' %}

{% block content %}
  <h1 class="display-4">Список книг</h1>
  {% if book_list %}
     <ul class="list-group">
       {% for book in book_list %}
         <li class="list-group-item">
          <a href="{% url 'book-detail' book.pk %}" class="btn btn-primary">{{ book.title }}</a>({{ book.genre.name }})
         <a href="update/{{book.id}}" class="btn btn-primary">Изменить</a>,
             <a href="delete/{{book.id}}" class="btn btn-primary">Удалить</a>
         </li>
       {% endfor %}
     </ul>
  {% else %}
    <p>В базе нет книг</p>
  {% endif %}
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends 'base_generic.html' %}

{% block content %}
<h1>Взятые книги</h1>
{% if bookinstance_list %}
<ul>
    {% for bookinstance in bookinstance_list %}
    <li class="{% if bookinstance.is_overdue %} text-danger {% endif %}">
       <a href="{% url 'book-detail' bookinstance.book.pk %}">

            {{ bookinstance.book.title }}
        </a> ({{ bookinstance.due_back }})
    </li>
    {% endfor %}
</ul>
{% else %}
<p>Нет книг со статусом в ЗАКАЗЕ</p>
{% endif %}
{% endblock %}

catalog/templates/catalog/edit1.html
{% extends "base_generic.html" %}

{% block content %}
<h3 class="mb-4">Список авторов из БД</h3>
<h4>{{ author.first_name }}  {{ author.last_name }}</h4>

<form method="post" class="row g-3">
  {% csrf_token %}
  <div class="col-md-6">
    <label class="form-label">Измените имя</label>
    <input type="text" name="first_name" value="{{ author.first_name }}" class="form-control">
  </div>
  <div class="col-md-6">
    <label class="form-label">Измените фамилию</label>
    <input type="text" name="last_name" value="{{ author.last_name }}" class="form-control">
  </div>
  <div class="col-md-6">
    <label class="form-label">Измените дату рождения</label>
    <input type="date" name="date_of_birth" value="{{ author.date_of_birth }}" class="form-control">
  </div>
  <div class="col-md-6">
    <label class="form-label">Измените дату смерти</label>
    <input type="date" name="date_of_death" value="{{ author.date_of_death }}" class="form-control">
  </div>
  <div class="col-12">
    <input type="submit" value="Сохранить" class="btn btn-primary">
  </div>
</form>
{% endblock %}